### ISSUE TITLE
Is it possible to create a similar filter for fluent-bit?

### ISSUE THREAD

**Issue by bilkoua** [fluent-plugins-nursery/geoip2_c#12]
Is it possible to create a similar filter for fluent-bit (https://github.com/fluent/fluent-bit)?
Thanks in advance for your reply.

**Comment by okkez** [comment]
It is possible to implement the filter plugin for fluent-bit using libmaxminddb.
Check the [document](https://docs.fluentbit.io/manual/development) carefully, please.
But this is a Ruby C extension library.
